flags: {}
extra-package-dbs: []
apply-ghc-options: locals
packages:
- '.'
extra-deps:
- FloatingHex-0.4
- Unixutils-1.54.1
- bzlib-0.5.0.5
- crackNum-1.9
- ghci-pretty-0.0.2
- ipprint-0.6
- sbv-7.1
- sr-extra-1.46.3.2
resolver: lts-9.0
